// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Topshelf")]
[assembly: AssemblyDescriptionAttribute("Topshelf is an open source project for hosting services without friction. By referencing Topshelf, your console application *becomes* a service installer with a comprehensive set of command-line options for installing, configuring, and running your application as a service.")]
[assembly: AssemblyProductAttribute("Topshelf")]
[assembly: AssemblyVersionAttribute("4.0.0.0")]
[assembly: AssemblyFileVersionAttribute("4.0.3.0")]
[assembly: AssemblyInformationalVersionAttribute("4.0.3.0")]
[assembly: AssemblyCopyrightAttribute("Copyright 2012 Chris Patterson, Dru Sellers, Travis Smith, All rights reserved.")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "4.0.0.0";
        internal const string InformationalVersion = "4.0.3.0";
    }
}
